name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: positive
      id: positive
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: positive
        setup-command: ''
        command: python multiply.py
        input: 3 5
        expected-output: '15'
        comparison-method: exact
        timeout: 10
    - name: Negative
      id: negative
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Negative
        setup-command: ''
        command: python multiply.py
        input: "-4 -6"
        expected-output: '24'
        comparison-method: exact
        timeout: 10
    - name: mixed
      id: mixed
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: mixed
        setup-command: ''
        command: python multiply.py
        input: 2 -4
        expected-output: "-8"
        comparison-method: exact
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        POSITIVE_RESULTS: "${{steps.positive.outputs.result}}"
        NEGATIVE_RESULTS: "${{steps.negative.outputs.result}}"
        MIXED_RESULTS: "${{steps.mixed.outputs.result}}"
      with:
        runners: positive,negative,mixed
